services:
  app:
    build: .
    command: python -u app.py
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
    depends_on:
      - db


  db:
    image: mongo:latest
    hostname: crud_mongodb
    environment:
      - MONGO_INITDB_DATABASE=crud_db
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=user
    ports:
      - 27017:27017